name: genemod_supplementary
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - polars=1.12.0
  - scipy=1.14.1
  - statsmodels=0.14.4
  - click=8.1.7
  - pytest=8.3.3
  - pandas=2.2.3  # Added as it appears to be a dependency
  - numpy=2.1.3   # Added as it's a core dependency
  - rdkit=2024.3.6
  - seaborn=0.13.0
  - pyarrow=18.0.0
  - tabulate=0.9.0
  - bioconda::mygene=3.2.1

